language: node_js
node_js:
  - "6"
before_script:
  - npm install -g bower
  - npm install -g mocha-phantomjs
  - npm install -g browserify
  - npm install -g uglifyify
  - bower install
  - npm run build-js
  - npm run build-js-min
script:
  - npm test
  - npm run test-client