os:
  - linux
language: node_js
node_js:
  - "6"
before_script:
  - npm install -g bower browserify uglifyify mocha-phantomjs 
  - bower install
  - npm run build-js && npm run build-js-min
script:
  - npm test
  - npm run test-client