language: node_js
node_js:
  - "6"
before_script:
  - npm install -g bower
  - bower install
  - npm install -g web-component-tester
  - 'export DISPLAY=:99.0'
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - 'echo "Client based testing..."'
  - wct test/client/index.test.js
  - 'echo "Server based testing..."'
script:
  - npm test
