echo "****************************************************"
echo "*                                                  *"
echo "*                                                  *"
echo "*                                                  *"
echo "*                                                  *"
echo "*                                                  *"
echo "*                                                  *"
echo "******* Build Workflow and Copy to mobile1.8 *******"
echo "*                                                  *"
echo "*                                                  *"
echo "*                                                  *"
echo "*                                                  *"
echo "*                                                  *"
npm run browserify
cp dist/workflow.js dist/workflow.min.js /Users/satinders/Development/mobile1.8/app/scripts/
echo "*                                                  *"
echo "*                                                  *"
echo "*                                                  *"
echo "*                                                  *"
echo "*                                                  *"
echo "*                                                  *"
echo "*                                                  *"
echo "*                                                  *"
echo "*                                                  *"
echo "*************** Build complete *********************"
